namespace GoodSamaritanNpc;

internal enum Msg
{
    SuspiciousBehavior,
    RevealingAction,
    CarryingSuspiciousItem,
    HiddenContraband,
    PickingContraband,
    AttackingCivilian,
    TacklingCivilian,
    Jumping,
    CuttingLine,
    DirectReport,
    AreaReport,
    AreaSecurityLine,
    AreaTerminal,
    AreaJail,
    AreaSmugglerRoom,
    AreaTsa,
    AreaLobby,
    AreaPlane,
    AreaCabin,
    AreaCockpit,
    AreaGalley,
    AreaCargo,
    AreaPlaneExterior,
    AreaGate,
    AreaRunway,
    AreaVending,
    AreaTower,
    AreaDeathmatch,
    AreaSandbox,
    AreaConveyor,
    AreaBreakRoom,
    AreaCurrentPosition,
    WitnessPrefix
}
